# main menu navigation
menu:
  Home: /
  # Categories: catagories
  # Tag: /tags/index.md
  Archive: archives
  About: about

widgets:
  - archive
  - tag
  - recent_posts
  - category
  - profile

# social config
social:
  zhihu:
  twitter: /
  facebook: /
  linkedin:
  instagram: /
  github: harisban

user:
  name: Haris Ban
  avatar: /images/avatar.jpg
  location: In the dust
  description: 從未與妳飲過冰,零度天氣看風景
  footnotes: # footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  # repo: Haojen/Claudia-theme-blog # your blog repo
  repo: HarisBan/harisban.github.io


# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

comment_disqus:
    enable: false
    url:   # the url of your website main domain like this https://xxx.xxx/
    name: # the short name in disqus

# dark
# light
# user-can-set
appearance: dark # Default value is auto

# Miscellaneous
favicon: /images/favicon.png

# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id:

# picture of about page
about_pic: about.png
